# SES Controller Configuration - Experiment 2 (Visual Occlusion)
# These parameters can be modified without rebuilding the package.
# If a parameter is not specified here, the default value in the code will be used.

experiment_name: "exp4_real_branch"  # Used for logging and saving results

# Controller timing
dt: 0.05
max_steps: 3500
num_modes: 15

# Parameter Bounds relative to the EE initial position
K_MIN_rel: -0.01    # X minimum offset
K_MAX_rel: 0.2   # X maximum offset
L1_MIN_rel: -0.25    # Z minimum offset
L1_MAX_rel: 0.28 #0.3   # Z maximum offset

# Features
n_feat: 3  # Total number of features on the rod (tracked or not)
tracked_feat: [0,1,2]  # Indexes of the features being tracked (starting from 0)

# Visualization settings
enable_visualization: true
viz_update_rate: 5  # Update visualization every N steps

# Progress-Variable Dynamics
gate_gamma: 5.0
gate_E_ref: 0.08 #0.08

# Temperature schedule: θ(s) = θ_0 / ln(e + λ_θ s)
theta_0: 5.0
lambda_theta: 7.0 #10.0

# Memory schedule: T(s) = T_0 * exp(-λ_T s)
T_0: 20.0 #20.0
lambda_T: 0.07 #0.1

# Mixing dynamics: dα/dt = κ_α θ(s)^2 ρ(E)
kappa_alpha: 0.01 #0.01

# Sobolev exponent
s_sobolev: 1.35

# Bayesian Parameters
sigma_apriori: 0.25
sigma_meas_norm: 0.01
sigma_likelihood: 0.025 #0.025

# Grid Setup
N_grid: 200
